site_name: Open States
site_url: https://openstates.github.io/documentation/
site_author: James Turk
site_description: Documentation for the Open States project.
copyright: Copyright &copy; 2021 Open States
repo_url: https://github.com/openstates/documentation
repo_name: openstates/documentation
edit_uri: edit/main/docs/

theme:
  logo: assets/openstates.svg
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - navigation.expand
    - navigation.top
    - navigation.sections
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/openstates
    - icon: fontawesome/brands/github
      link: https://github.com/openstates
markdown_extensions:
  - admonition
  - def_list
  - tables
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.superfences
  - toc:
      permalink: true
plugins:
- search
extra_css:
  - assets/extra.css
nav:
  - 'index.md'
  - 'code-of-conduct.md'
  - API v3:
    - 'api-v3/index.md'
    - 'api-v3/changelog.md'
  - GraphQL API:
    - 'api-v2/index.md'
    - 'api-v2/root-nodes.md'
    - 'api-v2/types.md'
    - 'api-v2/other.md'
    - 'api-v2/examples.md'
    - 'api-v2/changelog.md'
  - Contributing:
    - 'contributing/getting-started.md'
    - 'contributing/people.md'
    - 'contributing/scrapers.md'
    - 'contributing/openstates-org.md'
      # - 'contributing/text-extraction.md'
    - 'contributing/testing-scrapers.md'
    - 'contributing/state-specific.md'
    - 'contributing/documentation.md'
  - Data:
    - 'data/index.md'
    - 'data/categorization.md'
    - 'data/session-naming.md'
  - Enhancement Proposals:
    - 'enhancement-proposals/001-purpose-and-process.md'
    - 'enhancement-proposals/002-legal-citations.md'
    - 'enhancement-proposals/003-manual-people-data-tools.md'
    - 'enhancement-proposals/004-committee-data.md'
    - 'enhancement-proposals/005-dedupe-key.md'
    - 'enhancement-proposals/006-new-people-offices.md'
    - 'enhancement-proposals/007-events.md'
    - 'enhancement-proposals/008-active-sessions.md'
